# Generated by Django 6.0.2 on 2026-03-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caribbean_tours', '0002_cardtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtext',
            name='image_name',
            field=models.CharField(blank=True, default='default.jpg', help_text='Enter file name (eg Alicante.jpg)', max_length=100),
        ),
    ]
