# Generated by Django 6.0.2 on 2026-03-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caribbean_tours', '0003_alter_cardtext_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinations', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image_name', models.CharField(blank=True, default='default.jpg', help_text='Enter file name (eg Cancun).', max_length=100)),
            ],
        ),
    ]
