# Generated by Django 6.0.2 on 2026-03-18 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caribbean_tours', '0004_places'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardtext',
            options={'verbose_name': 'CardText', 'verbose_name_plural': 'CardTexts'},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AddField(
            model_name='places',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caribbean_tours.cardtext'),
        ),
    ]
