# Generated by Django 6.0.2 on 2026-03-20 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caribbean_tours', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='card',
        ),
        migrations.AddField(
            model_name='comment',
            name='places',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='caribbean_tours.places'),
        ),
    ]
