# Generated by Django 6.0.2 on 2026-03-20 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caribbean_tours', '0007_remove_comment_card_comment_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='caribbean_tours.places'),
        ),
    ]
